[project]
name = "crl-subgoal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "distrax>=0.1.5",
    "flax>=0.8.4",
    "jax[cuda12]>=0.4.26",
    "matplotlib>=3.10.3",
    "ml-collections>=1.1.0",
    "moviepy>=2.2.1",
    "ogbench>=1.1.2",
    "ruff>=0.11.11",
    "tqdm>=4.67.1",
    "tyro>=0.9.26",
    "wandb>=0.19.11",
    "xminigrid>=0.9.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
